use std::fs;
use std::path::Path;
use colored::Colorize;
use crate::utils;
use anyhow::{Context, Result, bail};

const PLUGINS_TOML: &str = r#"# Eiipm plugins manifest
# Add plugins in "user/repo" = "ref" format
# ref can be a branch, tag, or commit SHA
#
# Examples:
#   "user/repo" = "main"
#   "user/repo" = "v1.0.0"
#   "user/repo" = { ref = "main", build = "make release", artifact = "build/out.so" }

[plugins]
"#;

const PLUGINS_LOCK: &str = r#"# This file is automatically @generated by eiipm.
# It is not intended for manual editing.
version = 1
"#;

pub fn init_plugin_repo() -> Result<()> {
    let toml_path = Path::new("plugins.toml");
    let lock_path = Path::new("plugins.lock");

    if toml_path.exists() {
        bail!("plugins.toml already exists, this config is already initialized");
    }

    fs::write(toml_path, PLUGINS_TOML)
        .context("failed to create plugins.toml")?;
    log::info!("{} plugins.toml", "created".green().bold());

    fs::write(lock_path, PLUGINS_LOCK)
        .context("failed to create plugins.lock")?;
    log::info!("{} plugins.lock", "created".green().bold());

    fs::create_dir_all("plugins")
        .context("failed to create plugins/")?;
    log::info!("{} plugins/", "created".green().bold());

    if utils::confirm("Add plugins/ to .gitignore?") {
        add_to_gitignore()?;
    }

    log::info!("\n{} run {} to install plugins", "tip:".dimmed(), "eiipm install".cyan());
    Ok(())
}

fn add_to_gitignore() -> Result<()> {
    let gitignore_path = Path::new(".gitignore");
    let entry = "plugins/\n";

    if gitignore_path.exists() {
        let contents = fs::read_to_string(gitignore_path)
            .context("failed to read .gitignore")?;

        if contents.lines().any(|l| l.trim() == "plugins/") {
            log::info!("{} plugins/ already in .gitignore", "skipped".dimmed());
            return Ok(());
        }

        let mut appended = contents;
        if !appended.ends_with('\n') {
            appended.push('\n');
        }
        appended.push_str(entry);

        fs::write(gitignore_path, appended)
            .context("failed to update .gitignore")?;
    } else {
        fs::write(gitignore_path, entry)
            .context("failed to create .gitignore")?;
    }

    log::info!("{} plugins/ to .gitignore", "added".green().bold());
    Ok(())
}
