[book]
authors = ["Byson94"]
language = "en"
src = "src"
title = "eiipm documentation"

[output.html]
default-theme = "latte"
preferred-dark-theme = "macchiato"
git-repository-url = "https://github.com/Ewwii-sh/eiipm/"
additional-js = ["js/home_button.js"]
additional-css = ["./theme/catppuccin.css"]